adjust for DietPi

diff --git a/adafruit-pi-externalroot-helper b/adafruit-pi-externalroot-helper
--- a/adafruit-pi-externalroot-helper
+++ b/adafruit-pi-externalroot-helper
@@ -1,15 +1,20 @@
 #!/usr/bin/env bash
 
-# adafruit-pi-externalroot-helper
+# Based on adafruit-pi-externalroot-helper
 # 
-# Configure a Raspbian system to use an external USB drive as root filesystem.
+# Configure a DietPi system to use an external USB drive as root filesystem.
 #
 # See README.md for details and sources.
+
+if [[ ! -t 0 || ! -t 1 ]]; then
+    echo "Error: This script must be run in an interactive terminal."
+    exit 1
+fi
 
 set -e
 
 function print_version() {
-    echo "Adafruit Pi External Root Helper v0.1.0"
+    echo "DietPi External Root Helper v0.1.0"
     exit 1
 }
 
@@ -87,9 +92,9 @@ fi
 
 export target_partition="${target_drive}1"
 
-info "dependencies" "Installing gdisk, rsync, and parted."
+info "dependencies" "Installing rsync and parted."
     # All except gdisk are probably installed, but let's make sure.
-    apt-get install gdisk rsync parted
+    apt-get install rsync parted
 
 info "fs create" "Creating ${target_partition}"
     # The alternative here seems to be to pipe a series of commands
@@ -104,8 +109,8 @@ info "fs create" "Creating ${target_partition}"
     parted --script --align optimal "${target_drive}" mkpart primary ext4 0% 100%
 
 info "fs create" "Creating ext4 filesystem on ${target_partition}"
-    sleep 5
-    mkfs -t ext4 -L rootfs "${target_partition}"
+    sleep 3
+    mkfs -F -t ext4 -L rootfs "${target_partition}"
 
 info "fs id" "Getting UUID for target partition"
     eval `blkid -o export "${target_partition}"`
@@ -123,14 +128,14 @@ info "fs copy" "Mounting ${target_partition} on /mnt"
 
 info "fs copy" "Copying root filesystem to ${target_partition} with rsync"
 info "fs copy" "This will take quite a while.  Please be patient!"
-    rsync -ax / /mnt
+    rsync -ax --info=progress2 / /mnt
 
 info "boot config" "Configuring boot from {$target_partition}"
-    #rootwait is already in the file and is sufficient
-    cp /boot/cmdline.txt /boot/cmdline.txt.bak
-    sed -i "s|root=PARTUUID=\S\+ |root=PARTUUID=${partition_unique_partuuid} |g" /boot/cmdline.txt
+    # rootdelay=5 is likely not necessary here, but seems to do no harm.
+    cp /boot/dietpiEnv.txt /boot/dietpiEnv.txt.bak
+    sed -i "s|root=\(PARTUUID\|UUID\)=\S\+ |root=PARTUUID=${partition_unique_partuuid} |g" /boot/dietpiEnv.txt
 
-info "boot config" "Commenting out old root partition in /etc/fstab, adding new one"
+info "boot config" "Commenting out old root partition in /mnt/etc/fstab, adding new one"
     # These changes are made on the new drive after copying so that they
     # don't have to be undone in order to switch back to booting from the
     # SD card.
@@ -141,7 +146,7 @@ info "boot config" "Commenting out old root partition in /etc/fstab, adding new 
 
 info "boot config" "Ok, your system should be ready. You may wish to check:"
 info "boot config" "  /mnt/etc/fstab"
-info "boot config" "  /boot/cmdline.txt"
+info "boot config" "  /boot/dietpiEnv.txt"
 info "boot config" "Your new root drive is currently accessible under /mnt."
 info "boot config" "In order to restart with this drive at /, please type:"
 info "boot config" "sudo reboot"
